title: "BYU Recruiting Prediction Project"
description: "This project predicts the probability that a football recruit will commit to BYU."
theme: minima

header_pages:
  - index.md
  - functions.md
  - tutorial.md

github_username: brooke-seeley